name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
  combine:
    name: Combine Artifacts
    needs: build
    uses: ./.github/workflows/combine-artifacts.yml
    with:
      output-name: "OpenXR-API-Layers-GUI-v${{needs.build.outputs.version}}"
    secrets: inherit