name: Combine Artifacts
on:
  workflow_call:
    inputs:
      output-name:
        required: true
        type: string
jobs:
  combine:
    name: Combine Artifacts
    runs-on: windows-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{runner.temp}}/artifacts
          merge-multiple: true
      - name: List artifacts
        run: Get-ChildItem -Recurse ${{runner.temp}}/artifacts
      - name: Delete version.txt
        run: Remove-Item ${{runner.temp}}/artifacts/version.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{inputs.output-name}}"
          path: ${{runner.temp}}/artifacts